name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: iOS build and tests
      run: xcodebuild test -scheme "MCCPlacement (iOS)" -destination platform\=iOS\ Simulator,OS\=14.2,name\=iPhone\ 8

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: macOS build and tests
      run: xcodebuild test -scheme "MCCPlacement (macOS)" -destination platform\=macOS

